import { DocsComponentCategory } from './docs-component-category';
import { AppRoutePath } from '../navigation/app-route-path';

export const DOCS_COMPONENT_CATEGORIES: readonly DocsComponentCategory[] = [
  {
    label: 'Actions',
    description: 'Trigger commands, menus, and command-style workflows.',
    components: [
      {
        name: 'Button',
        importName: 'KuiButtonDirective',
        status: 'available',
        description: 'Primary command primitive for buttons and links.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsButton}`,
      },
      {
        name: 'Icon Button',
        importName: 'KuiIconButtonDirective',
        status: 'available',
        description: 'Compact icon-only action control.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsIconButton}`,
      },
      {
        name: 'Menu',
        importName: 'KuiMenuComponent',
        status: 'available',
        description: 'Anchored command menu with keyboard focus behavior.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsMenu}`,
      },
      {
        name: 'Command Palette',
        importName: 'KuiCommandPaletteComponent',
        status: 'available',
        description: 'Searchable command overlay for application actions.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsCommandPalette}`,
      },
    ],
  },
  {
    label: 'Forms',
    description: 'Field wiring, native controls, and overlay-backed input patterns.',
    components: [
      {
        name: 'Field',
        importName: 'KuiFieldComponent',
        status: 'available',
        description: 'Label, hint, error, and form-control composition.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsField}`,
      },
      {
        name: 'Input',
        importName: 'KuiInputDirective',
        status: 'available',
        description: 'Native text input styling with field integration.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsInput}`,
      },
      {
        name: 'Select',
        importName: 'KuiSelectDirective',
        status: 'available',
        description: 'Dropdown-backed selection control for single and multiple values.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsSelect}`,
      },
      {
        name: 'Combobox',
        importName: 'KuiComboboxDirective',
        status: 'docs-pending',
        description: 'Searchable input with projected options and async mode.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsCombobox}`,
      },
      {
        name: 'Slider',
        importName: 'KuiSliderDirective',
        status: 'docs-pending',
        description: 'Native range input styling with field and Signal Forms support.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsSlider}`,
      },
      {
        name: 'Number Input',
        importName: 'KuiNumberInputDirective',
        status: 'docs-pending',
        description: 'Number input states with compact variant options.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsNumberInput}`,
      },
      {
        name: 'Textarea',
        importName: 'KuiTextareaDirective',
        status: 'available',
        description: 'Native multiline input styling with field integration.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsTextarea}`,
      },
      {
        name: 'Checkbox',
        importName: 'KuiCheckboxDirective',
        status: 'available',
        description: 'Native checkbox styling with field state integration.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsCheckbox}`,
      },
      {
        name: 'Switch',
        importName: 'KuiSwitchDirective',
        status: 'available',
        description: 'Native switch control styling for binary settings.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsSwitch}`,
      },
      {
        name: 'Radio',
        importName: 'KuiRadioDirective',
        status: 'docs-pending',
        description: 'Native radio control styling for exclusive choices.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsRadio}`,
      },
      {
        name: 'Group',
        importName: 'KuiGroupDirective',
        status: 'docs-pending',
        description: 'Grouped control chrome for adjacent actions and fields.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsGroup}`,
      },
    ],
  },
  {
    label: 'Feedback',
    description: 'Status, loading, empty, and notification primitives.',
    components: [
      {
        name: 'Badge',
        importName: 'KuiBadgeDirective',
        status: 'docs-pending',
        description: 'Compact status or metadata marker.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsBadge}`,
      },
      {
        name: 'Loader',
        importName: 'KuiLoaderDirective',
        status: 'docs-pending',
        description: 'Inline loading indicator for buttons and status areas.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsLoader}`,
      },
      {
        name: 'Skeleton',
        importName: 'KuiSkeletonDirective',
        status: 'docs-pending',
        description: 'Loading placeholder with reduced-motion behavior.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsSkeleton}`,
      },
      {
        name: 'Toast',
        importName: 'KuiToastService',
        status: 'docs-pending',
        description: 'Global notifications with actions and live-region semantics.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsToast}`,
      },
      {
        name: 'Empty State',
        importName: 'KuiEmptyStateComponent',
        status: 'docs-pending',
        description: 'Known empty, error, no-access, and success content states.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsEmptyState}`,
      },
      {
        name: 'Progress',
        importName: 'KuiProgressComponent',
        status: 'docs-pending',
        description: 'Progress status primitive for determinate and indeterminate work.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsProgress}`,
      },
    ],
  },
  {
    label: 'Surfaces',
    description: 'Containers, disclosure patterns, overlays, and structural primitives.',
    components: [
      {
        name: 'Card',
        importName: 'KuiCardDirective',
        status: 'docs-pending',
        description: 'Surface, elevated, and sunken content container.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsCard}`,
      },
      {
        name: 'Tabs',
        importName: 'KuiTabsComponent',
        status: 'docs-pending',
        description: 'Line and pill tab navigation with optional panel wiring.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsTabs}`,
      },
      {
        name: 'Accordion',
        importName: 'KuiAccordionComponent',
        status: 'docs-pending',
        description: 'Disclosure component for grouped expandable content.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsAccordion}`,
      },
      {
        name: 'Popover',
        importName: 'KuiPopoverComponent',
        status: 'docs-pending',
        description: 'Anchored content surface for contextual UI.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsPopover}`,
      },
      {
        name: 'Dialog',
        importName: 'kuiDialog',
        status: 'docs-pending',
        description: 'Typed modal overlay service and host contract.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsDialog}`,
      },
      {
        name: 'Drawer',
        importName: 'kuiDrawer',
        status: 'docs-pending',
        description: 'Side and edge overlay surface for focused workflows.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsDrawer}`,
      },
      {
        name: 'Dropdown',
        importName: 'KuiDropdownComponent',
        status: 'docs-pending',
        description: 'Projected option overlay used by select-like controls.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsDropdown}`,
      },
      {
        name: 'Separator',
        importName: 'KuiSeparatorDirective',
        status: 'docs-pending',
        description: 'Tokenized horizontal or vertical separator primitive.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsSeparator}`,
      },
    ],
  },
  {
    label: 'Data and Identity',
    description: 'Tables, avatars, chips, icons, and scroll containers.',
    components: [
      {
        name: 'Avatar',
        importName: 'KuiAvatarComponent',
        status: 'docs-pending',
        description: 'User or entity identity with image, initials, and status.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsAvatar}`,
      },
      {
        name: 'Table',
        importName: 'KuiTableDirective',
        status: 'docs-pending',
        description: 'Native table styling, sorting context, and selection cells.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsTable}`,
      },
      {
        name: 'Chip',
        importName: 'KuiChipDirective',
        status: 'docs-pending',
        description: 'Compact token for selected values, filters, and entity references.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsChip}`,
      },
      {
        name: 'Scrollbar',
        importName: '.kui-scroll',
        status: 'docs-pending',
        description: 'Tokenized native scroll container utility.',
        routePath: `/${AppRoutePath.Components}/${AppRoutePath.ComponentsScrollbar}`,
      },
    ],
  },
];
